### ISSUE TITLE
How to define location like in RA?

### ISSUE THREAD

**Issue by BogdanScherban** [BogdanScherban/Lerna-PulseTile#4]
@djhi 
Hi, Gildas! Could you please help me with this issue?

**What I want to do:**
Each `project/ `of our Lerna (Helm, Showcase, Scotland and London) should have custom Topbar with logo, additional buttons, banner about patient, etc. 
I wanted to create custom Topbar module in each project separately and pass it to my package **"pulsetile-react-admin"** as a property.

**How I did this:**
I created custom Layout with Topbar, Footer, Sidebar and some current project settings:
https://github.com/BogdanScherban/Lerna-PulseTile/blob/master/projects/helm/src/custom/Layout.js

And passed it to my package:
```
// projects/helm/src/App.js

import React, { Component } from 'react';

import { App, PatientSummaryPage } from "pulsetile-react-admin";

import * as themeConfiguration from "./custom/themeConfig";
import CustomLayout from "./custom/Layout";

class Core extends Component {
  render() {
    return (
        <App
            themeConfiguration={themeConfiguration}
            CustomLayout={CustomLayout}
            CustomHomepage={PatientSummaryPage}
        />
    )

  }
}

export default Core;
```

**Where is my problem:**
It works correctly, but I found a problem. My custom Topbar need in **location** property:
```
....
....
   render() {
        const { classes, isSidebarOpen, setSidebarVisibility, patientInfo } = this.props;

        const location = window.location;
        console.log('window.location', window.location)
        
        // HERE I NEED IN LOCATION
        const isPageHasTitle = pageHasTitle(location);
        const isPageHasPatientBanner = pageHasPatientBanner(location);
        
        return (
                ....
        );
    }
};
...
```
In React-Admin this props comes automatically, but in my custom Layout it is absent. 

I tried to use **windows.location** object for this, but it isn't changed when we change URL (because Topbar isn't re-rendered when we do it).

Can we use **location** from React-Admin here? 
Or can we solve this problem by the other way?

**Comment by djhi** [comment]
Use the `withRouter` HOC from react-router. See https://reacttraining.com/react-router/web/api/withRouter

**Comment by BogdanScherban** [comment]
Thanks, @djhi - it works!
